
import { ResponsiveContainer } from "@/components/layout/ResponsiveContainer";

export function TestimonialsSection() {
  return (
    <section id="testimonials" className="py-20 md:py-32 bg-accent/50" aria-labelledby="testimonials-heading">
      <ResponsiveContainer>
        <div className="text-center mb-16">
          <h2 id="testimonials-heading" className="text-3xl md:text-4xl font-bold mb-4">What Accounting Teams Say</h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Industry professionals trust Gaapio for their accounting documentation needs.
          </p>
        </div>
        
        <div className="grid md:grid-cols-3 gap-8">
          {/* Testimonial 1 */}
          <div className="bg-background rounded-lg p-6 shadow-sm">
            <p className="mb-4 italic">
              "Gaapio has transformed our month-end close process. What used to take hours now takes minutes, with even better quality."
            </p>
            <div className="flex items-center">
              <div className="w-10 h-10 bg-primary/10 rounded-full flex items-center justify-center mr-3" aria-hidden="true">
                <span className="font-medium">JD</span>
              </div>
              <div>
                <p className="font-medium">Jane Doe</p>
                <p className="text-sm text-muted-foreground">VP Finance, Enterprise Co.</p>
              </div>
            </div>
          </div>
          
          {/* Testimonial 2 */}
          <div className="bg-background rounded-lg p-6 shadow-sm">
            <p className="mb-4 italic">
              "The accounting memos generated by Gaapio are consistently accurate and thorough. Our audit team has been impressed."
            </p>
            <div className="flex items-center">
              <div className="w-10 h-10 bg-primary/10 rounded-full flex items-center justify-center mr-3" aria-hidden="true">
                <span className="font-medium">JS</span>
              </div>
              <div>
                <p className="font-medium">John Smith</p>
                <p className="text-sm text-muted-foreground">Controller, Tech Inc.</p>
              </div>
            </div>
          </div>
          
          {/* Testimonial 3 */}
          <div className="bg-background rounded-lg p-6 shadow-sm">
            <p className="mb-4 italic">
              "As a CPA, I was skeptical of AI-written memos, but Gaapio has proven to be an invaluable assistant to our accounting team."
            </p>
            <div className="flex items-center">
              <div className="w-10 h-10 bg-primary/10 rounded-full flex items-center justify-center mr-3" aria-hidden="true">
                <span className="font-medium">AW</span>
              </div>
              <div>
                <p className="font-medium">Amanda Wilson</p>
                <p className="text-sm text-muted-foreground">Senior CPA, Accounting Partners</p>
              </div>
            </div>
          </div>
        </div>
      </ResponsiveContainer>
    </section>
  );
}

