// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxojxrcerefklsrqkmrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4b2p4cmNlcmVma2xzcnFrbXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDQwODksImV4cCI6MjA2MDkyMDA4OX0.-zeHbPQbjHG5sHMS6985h_FKcPuPo1yUEU2ucRZHil8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);