
name: Deploy to GitHub Pages

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Verify logo assets exist
        run: |
          mkdir -p public/assets/images
          if [ ! -f "public/assets/images/logo-light.png" ] || [ ! -f "public/assets/images/logo-dark.png" ]; then
            echo "Warning: Logo files missing. Deployment may have display issues."
            # Create empty placeholder files to prevent build failures
            touch public/assets/images/logo-light.png
            touch public/assets/images/logo-dark.png
          else
            echo "Logo files verified successfully!"
          fi
      - name: Build
        run: npm run build
      - name: Prepare asset directories
        run: |
          mkdir -p dist/assets/images
          cp -r public/assets/images/* dist/assets/images/ || true
          echo "Asset verification:"
          ls -la dist/assets/images/
      - name: Copy index.html to 404.html for client-side routing
        run: |
          cp dist/index.html dist/404.html
      - name: Create _headers file
        run: |
          cat > dist/_headers << EOL
          /*
            Strict-Transport-Security: max-age=31536000; includeSubDomains
            X-Content-Type-Options: nosniff
            X-Frame-Options: DENY
            X-XSS-Protection: 1; mode=block
          EOL
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
