
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Create assets directory for images
        run: mkdir -p public/assets/images
        
      - name: Copy lovable-uploads to assets/images
        run: cp -R public/lovable-uploads/* public/assets/images/ || true
        
      - name: Build
        run: npm run build
        
      - name: Add .nojekyll file
        run: touch dist/.nojekyll
        
      - name: Ensure assets directories exist
        run: |
          mkdir -p dist/assets/images
          
      - name: Copy public images to dist assets
        run: |
          cp -R public/assets/images/* dist/assets/images/ || true
          cp -R public/lovable-uploads/* dist/assets/images/ || true
          cp -R public/_headers dist/ || true
        
      - name: Create proper MIME type configuration
        run: |
          echo "/* /index.html 200" > dist/_redirects
          if [ ! -f dist/_headers ]; then
            cat > dist/_headers << EOL
            /*
              Content-Type: text/html
            *.js
              Content-Type: text/javascript
            *.tsx
              Content-Type: text/javascript
            *.css
              Content-Type: text/css
            *.json
              Content-Type: application/json
            *.png
              Content-Type: image/png
            *.jpg
              Content-Type: image/jpeg
            *.svg
              Content-Type: image/svg+xml
            EOL
          fi
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
